### ISSUE TITLE
Feature: lazy parsing

### ISSUE THREAD

**Issue by bsless** [cnuernber/charred#1]
Would it be possible to provide a lazy reader which returns a reducible (or kvreducible) over the top level element?
For CSV it would return one line at a time, for JSON array one element at a time, and for a JSON object it would be a KV reducible over keys and values.

**Comment by cnuernber** [comment]
CSV parsing is lazy and the returned supplier could definitely implement reducible.  The JSON parsing is 'lazy' if you have many JSON objects at the top level of your stream but most people save JSON data with a single top level JSON object which gets greedily parsed out.
  
The harder case for JSON is what if you have a single mammoth JSON object and you want to lazily parse that - I think for that pathway you need a sort of SAX interface and let the user manually drive the parser.  Still totally doable but you don't really know what the top JSON object is so it might be an array, an object, or a JSON primitive - string number boolean or null.

**Comment by cnuernber** [comment]
If [this object](https://github.com/cnuernber/charred/blob/master/src/charred/api.clj#L190) implements ISeq and IReducible correctly then we are a step further.  Perhaps then the CSV engine has a profile like the JSON does where you can specify immutable vs. mutable and then everything works the same.  That solves the CSV pathway completely.

For the JSON pathway I think we need to think about it a bit more.
