### ISSUE TITLE
Column quoting behavior. `read-csv` vs `read-csv-supplier`

### ISSUE THREAD

**Issue by carlosgeos** [cnuernber/charred#19]
Hi ! I've had a minor issue parsing column headers out of a CSV file (which I admit, has some columns which are unnecessarily double quoted) and I'd just like to know if the following is expected:

1. Reading a simple string:
```clojure
(ch/read-csv "\"ID\",\"Name\"")
=> (["ID" "Name"]) ;; This is fine, wrapped in a seq or otherwise
```
2. Reading the following contents out of a CSV file:
```
# contents of debug.csv
"ID","Name"
```
```clojure
(def supp (ch/read-csv-supplier (io/resource "csv/debug.csv")))
(.get supp)
=> ["﻿\"ID\"" "Name"]
```

Why are (only) the first column's double quotes escaped ? It seems like the `:quote` option being `\"` by default is working well for the rest of the columns, just not the first one.

**Comment by cnuernber** [comment]
That is a great question - we are going to track it down.

**Comment by carlosgeos** [comment]
It is indeed an issue with the BOM !! Thanks for the tip. I also couldn't reproduce the issue with a new file created with Emacs. The differences (debug.csv being the one with BOM and debug2.csv the one without):
```
$ file debug.csv
debug.csv: Unicode text, UTF-8 (with BOM) text, with no line terminators
```
vs
```
$ file debug2.csv
debug2.csv: ASCII text, with no line terminators
```

And the binary output of both:
```
$ hexdump -C debug.csv
00000000  ef bb bf 22 49 44 22 2c  22 4e 61 6d 65 22        |..."ID","Name"|
0000000e
```
vs
```
$ hexdump -C debug2.csv
00000000  22 49 44 22 2c 22 4e 61  6d 65 22                 |"ID","Name"|
0000000b
```
