### ISSUE TITLE
:close-writer? should probably not be true by default

### ISSUE THREAD

**Issue by kanwei** [cnuernber/charred#21]
I tried doing a drop-in replacement for data.csv but :close-writer? is true by default and it's not for data.csv.

**Comment by cnuernber** [comment]
Completely agreed

**Comment by cnuernber** [comment]
Fixed in 1.029

**Comment by kanwei** [comment]
@cnuernber Thanks, but it doesn't look to be fixed - it's still true on 1.029

<img width="1209" alt="image" src="https://github.com/cnuernber/charred/assets/16632/32b2a522-5cbf-4ae9-b11d-44c688d39057">

**Comment by cnuernber** [comment]
Ha - I read that as close-reader?.

close-writer *also* should default to false like you say.

**Comment by cnuernber** [comment]
OK - 1.030 - let me know what you think.

**Comment by cnuernber** [comment]
Also - if you have minute please let me know what you think of the [bulk namespace](https://cnuernber.github.io/charred/charred.bulk.html).

**Comment by kanwei** [comment]
Thanks! The writer works for us now. We're not doing anything with multiple files, but those functions do look cool!

**Comment by cnuernber** [comment]
@kanwei - Do you load [large csvs](https://cnuernber.github.io/charred/charred.bulk.html#var-batch-csv-rows)?
