### ISSUE TITLE
Escaping double quotes not working if they appear right after `\n`

### ISSUE THREAD

**Issue by carlosgeos** [cnuernber/charred#29]
Hi ! just opening this issue to hopefully figure out if the following is expected behavior:

When parsing a CSV with the following contents:
```csv
"a","b"
"""text\n"", more text","never parsed"
```
The resulting map is:
```clojure
[{:a "\"textn\"", :b "more text\""}]
```
but I would expect it to be something like:
```clojure
[{:a "\"textn\", more text", :b "never parsed"}]
```
---
A simple test is:
```clojure
(ch/read-csv (clojure.java.io/file "charred-test.csv"))
;; => (["a" "b"] ["\"textn\"" "more text\"" "never parsed"])
```
where `(count (second <that thing>))` is 3, and I'd like it to be 2.

The `n` is not important; if happens for `a`, `z`, etc:
```clojure
;; CSV content
"a","b"
"""text\z"", more text","never parsed"

;; Resulting map:
[{:a "\"textz\"", :b "more text\""}]
```
This doesn't happen if there is whitespace between the backslash-char and the double (escaped) double quote:
```clojure
;; CSV content
"a","b"
"""text\z "", more text","it is parsed!"

;; Resulting map:
[{:a "\"textz \", more text", :b "it is parsed!"}]
```
---
LibreOffice is OK with the same CSV:
![Screenshot_20241107_204942](https://github.com/user-attachments/assets/17a36d90-c585-4053-a1c1-9d9e942ec867)

Thanks !

**Comment by cnuernber** [comment]
Not sure about the repro here:

```clojure
(def ^:private exquote
  "\"a\",\"b\"
\"\"\"text\n\"\", more text\",\"never parsed\"")

charred.csv-test> (println exquote)
"a","b"
"""text
"", more text","never parsed"
nil


charred.csv-test> (api/read-csv exquote)
(["a" "b"] ["\"text\n\", more text" "never parsed"])
```

I believe that is the same output as libreoffice.

**Comment by carlosgeos** [comment]
Sorry, I forgot mentioning I was using `[com.cnuernber/charred "1.017"]`  :man_facepalming: 

I can now see the change log for 1.018 and 1.019 talks exactly about this. 1.034 (latest) works fine. 

---
The repro for 1.017 was (with an extra backslash):
```clojure
(def ^:private exquote
  "\"a\",\"b\"
\"\"\"text\\n\"\", more text\",\"never parsed\"")

(api/read-csv exquote)
=> (["a" "b"] ["\"textn\"" "more text\"" "never parsed"])
```
