### ISSUE TITLE
About default behaviour of keywords serialisation

### ISSUE THREAD

**Issue by BrunoBonacci** [cnuernber/charred#3]
Hi Chris,

Firstly, I would like to thank you for your library.
I have a question about the serialisation of keywords, specifically about namespaced keywords.

I understand that one of your design goals for `Charred` is to be a drop-in replacement for `org.clojure/data.json`, however, my concern applies to the latter as well.

Looking at the following example of code, as you can see, the default `Charred` behaviour for the keyword serialisation is to serialise the keyword name only (without the namespace).

``` Clojure
(require '[charred.api :as charred])
(println (charred/write-json-str {:foo/bar "a" :b :foo/bar}))
;; {
;;   "bar": "a",
;;   "b": "bar"
;; }
```

This behaviour is the same as `org.clojure/data.json` however it is in contrast with the other two popular choices for JSON serialisation in Clojure.

``` Clojure
(require '[cheshire.core :as cheshire])
(println (cheshire/generate-string {:foo/bar "a" :b :foo/bar}))
;; {"foo/bar":"a","b":"foo/bar"}
```

``` Clojure
(require '[jsonista.core :as jasonista])
(println (jasonista/write-value-as-string {:foo/bar "a" :b :foo/bar}))
;; {"foo/bar":"a","b":"foo/bar"}
```

I would like to argue that `Chesire` and `Jasonista` have a better approach in regards to serialising keywords.

If the payload contains a namespaced keyword is probably because the namespace is an important part of the information described by the data value. In any case, I don't think it is a good thing for the library to arbitrarily elide this information.

One could argue that it is possible to change this behaviour via the appropriate protocol extension `PtoJSON`,
however, my counterargument is that by doing so, the change will apply to the whole system (whole runtime) and not just to the particular JSON serialisation call.
A system-wide change could have a bad effect somewhere else where this behaviour is not expected.

Since keywords are widely used in Clojure, both: as keys for maps and values, it makes sense to have a special treatment for them.

I'd like to suggest that the default behaviour for a keyword serialisation is to preserve the namespace where present and that there is an option to provide an alternative behaviour as a parameter for `write-json` function.

For example, `write-json` could accept a `:keyword-fn` where a different function could be provided to serialise keywords (as keys for maps and values as well)
`Cheshire` and `Jasonista` are excellent libraries, but the opportunity to have a zero-dependency JSON serialisation library which is at the same time highly performant is something that I personally really care about.

I'd like to hear your thoughts on this.

regards,
Bruno

**Comment by cnuernber** [comment]
Bruno - it is great to hear from you -- and I am really happy this library fits in your software world!.  

* 100% agreed.  Keywords (and symbols) should be serialized/hydrated with their respective namespaces and I think if nothing changes they `:key-fn` `keyword` will correct deserialize them.  I also think that is a safe and backwards-compatible change.

**Comment by BrunoBonacci** [comment]
Fantastic, thank you.

**Comment by cnuernber** [comment]
Release 1.005.  Related unit test - https://github.com/cnuernber/charred/blob/master/test/charred/json_test.clj#L226.
