### ISSUE TITLE
Issue when parsing to string when data includes a set

### ISSUE THREAD

**Issue by domparry** [cnuernber/charred#6]
Hi Chris,

Ed has found an issue (https://github.com/ngrunwald/datasplash/issues/123) with how strings are generated that is different from clojure.data and cheshire. For example:

```
{:id "15" :vals #{{:id "44" :views 4} {:id "492" :views 59}}}
```
from charred results in:
```
"{\"id\":\"15\",\"vals\":\"#{{:id \\\"492\\\", :views 59} {:id \\\"44\\\", :views 4}}\"}"
```
but from cheshire results in:
```
"{\"id\":\"15\",\"vals\":[{\"id\":\"492\",\"views\":59},{\"id\":\"44\",\"views\":4}]}"
```
and clojure.data results in:
```
"{\"id\":\"15\",\"vals\":[{\"id\":\"492\",\"views\":59},{\"id\":\"44\",\"views\":4}]}"
```

clojure.data and cheshire both handle the set as an array in json. Is there a way we can align with those libraries, even if it's through an option?

**Comment by domparry** [comment]
Forgot to mention, we're on charred 1.007 for the above.

**Comment by domparry** [comment]
Thanks so much! Also happy to submit a PR next time.

**Comment by cnuernber** [comment]
A PR would be very much appreciated :-).

**Comment by edporras** [comment]
Thanks so much guys!
